### ISSUE TITLE
extentreports-cucumber7-adapter is not working with Cucumber-JVM version 7.3.1

### ISSUE THREAD

**Issue by ashirbad1986** [grasshopper7/extentreports-cucumber7-adapter#8]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.971 s <<< FAILURE! - in TestSuite
[ERROR] CucumberFrameWork.BDD.Runner.TestRunner.runScenario  Time elapsed: 0.167 s  <<< FAILURE!
**java.lang.NoClassDefFoundError: io/cucumber/gherkin/Gherkin
Caused by: java.lang.ClassNotFoundException: io.cucumber.gherkin.Gherkin**

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestRunner>AbstractTestNGCucumberTests.runScenario:35 » NoClassDefFound io/cuc...
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.527 s
[INFO] Finished at: 2022-04-22T14:45:37+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project Automation: There are test failures.
[ERROR] 
[ERROR] Please refer to D:\TherapyBrands_Automation\BedManagementAutomation\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project Automation: There are test failures.

Please refer to D:\TherapyBrands_Automation\BedManagementAutomation\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to D:\TherapyBrands_Automation\BedManagementAutomation\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
	at org.apache.maven.plugin.surefire.SurefireHelper.throwException(SurefireHelper.java:271)
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:159)
	at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:435)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1079)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:889)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by grasshopper7** [comment]
Cucumber introduced changes in 7.3.0 which are meant to be internal but unfortunately the adapter depends on them. Pretty easy to change the code but need to do some testing. Till then u can downgrade the cucumber to 7.2.3.

**Comment by ashirbad1986** [comment]
> Cucumber introduced changes in 7.3.0 which are meant to be internal but unfortunately the adapter depends on them. Pretty easy to change the code but need to do some testing. Till then u can downgrade the cucumber to 7.2.3.

Thanks for the respond. I have already downgraded to v7.2.3 for the time being. For now I will waitfor the new relaese by you

**Comment by grasshopper7** [comment]
New release 1.4.1 has been uploaded to maven. Should be available later today or tomorrow. Check it and let me know.

**Comment by ashirbad1986** [comment]
> New release 1.4.1 has been uploaded to maven. Should be available later today or tomorrow. Check it and let me know.

Thanks I ll check and update you.

**Comment by ashirbad1986** [comment]
Hi @grasshopper7 ,

With the new version(1.4.1), I am able to use Cucumber v7.3.x with PlayWright. However when I used the same with Selenium(4.1.3)  the "until"  method of Fluentwait started throwing error.

Error Snippet:
**"The method until(Function<? super WebDriver,T>) in the type Wait<WebDriver> is not applicable for the arguments (ExpectedCondition<WebElement>)"**

**Comment by grasshopper7** [comment]
I do not think this has any connection to the adapter. It is most probably related to selenium 4. Have you checked on stackoverflow. Maybe this helps - https://groups.google.com/g/selenium-users/c/XSg-fANE9t0
Downgrade to 3.14... and check.

**Comment by ashirbad1986** [comment]
> I do not think this has any connection to the adapter. It is most probably related to selenium 4. Have you checked on stackoverflow. Maybe this helps - https://groups.google.com/g/selenium-users/c/XSg-fANE9t0 Downgrade to 3.14... and check.

Actualy Cucumber adapter version 1.3.2 is working well with Selenium v4.1.3

**Comment by grasshopper7** [comment]
Can u send me a sample code which is throwing the exception? Will try to replicate. Add the relevant stacktrace.

**Comment by grasshopper7** [comment]
I added this code to test, in the sample implementation.

`		WebDriverWait waitDrv = new WebDriverWait(driver, Duration.ofMinutes(1));
		waitDrv.until(ExpectedConditions.or(ExpectedConditions.titleContains("GitHub"),
				ExpectedConditions.titleContains("Stack Overflow")));`

It workd. R u trying something similar?

**Comment by ashirbad1986** [comment]
> 

Hi I got the issue. Its not because of  "**extentreports-cucumber7-adapter**". I am using SureFire reporter plugin and the latest version(3.0.0-M6) of that is not yet compatible with selenium 4. After reverting it to a earlier version everything worked fine.
I am sorry for the confusion and really appriciated your effort and time to give us a fix.
